"""
aplicar_notas_universitarias.py — Aplica as decisões editoriais do curador ao 3º lote
DHnet (8 comissões UNIVERSITÁRIAS), em fontes.json E na tabela `fontes` do Supabase.

Idempotente: pode ser rodado mais de uma vez. Só toca a tabela `fontes`
(nota_contexto e subtipo vivem na fonte; a busca faz join — os chunks NÃO precisam
ser atualizados; chunks.nota_contexto fica nulo e cai na da fonte via coalesce,
ver migração 0009).

Decisões (relatório de curadoria do 3º lote, aprovadas pelo Yuri):
- nota_contexto definitiva para as 8 fontes (substitui o texto provisório do engenheiro).
- UNIFESP: subtipo='informe' — o arquivo no DHnet é um INFORME ao Consu (versão
  reduzida, capítulos selecionados), não o relatório integral.
- E-mails de membros na capa da UFBA e reclassificação de paratexto: NÃO tratados
  aqui — registrados no backlog de qualidade em docs/fontes-prioritarias.md (não-bloqueante).

COMO RODAR:
  cd pipeline && .venv/bin/python aplicar_notas_universitarias.py
"""

import json
import os
from pathlib import Path

from dotenv import load_dotenv
from supabase import create_client

RAIZ = Path(__file__).resolve().parent
CATALOGO = RAIZ / "fontes.json"
load_dotenv(RAIZ.parent / ".env.local")
load_dotenv(RAIZ / ".env.local")

NOTAS = {
 "cuv-ba-ufba": "Relatório Final da Comissão Milton Santos de Memória e Verdade da Universidade Federal da Bahia (UFBA), publicado em Salvador, 18 de agosto de 2014. A comissão foi criada pela Resolução do Consuni nº 10/2013, de 25 de outubro de 2013, e instalada em dezembro daquele ano, em resposta à criação da Comissão Nacional da Verdade (Lei 12.528/2011). O nome homenageia o geógrafo Milton Santos, baiano, docente da UFBA e perseguido pelo regime. Composição tripartite (docentes, discentes, servidor técnico-administrativo); mandato encerrado em agosto de 2014. O relatório investiga as violações cometidas contra a comunidade da UFBA entre 1964 e 1985: invasão da Residência Universitária na madrugada de 31 de março para 1º de abril de 1964 (cerca de 50 estudantes presos e agredidos); prisões e perseguições a docentes, discentes e servidores; adesão de parte da direção universitária ao golpe (documentada em atas do Consuni); funcionamento da AESI como aparato de espionagem interna subordinado à DSI/MEC; cassações e indeferimentos de matrícula por 'determinação superior'. A seção 'Os Perseguidos' (p. 55–139) lista individualmente os casos identificados. Base documental: correspondência sigilosa do Gabinete do Reitor (1964–1981), atas de congregações e do Consuni, documentos de unidades de ensino, 29 depoimentos. ALERTA DE USO: o relatório declara explicitamente que seus resultados são parciais, que a documentação da UFBA está dispersa e não tratada arquivisticamente, e que a relação de perseguidos poderá ser ampliada por pesquisa futura; informações factuais individuais devem ser cotejadas com a CNV Vol. III e o CEMDP. Proveniência: DHnet redistribui o PDF original da UFBA sem alterações — mesmo padrão adotado para o CEMDP neste acervo.",
 "cuv-df-unb": "Relatório Final da Comissão Anísio Teixeira de Memória e Verdade da Universidade de Brasília (CATMV-UnB), publicado em setembro de 2015 pela FAC-UnB. A comissão foi criada pela Resolução da Reitoria nº 85/2012, de 10 de agosto de 2012, e encerrou os trabalhos em abril de 2015 — entre as primeiras comissões universitárias a concluir e a maior deste lote (363 p.). O nome homenageia Anísio Teixeira, educador e primeiro reitor da UnB, cujas circunstâncias de morte em 1971 são investigadas no relatório. Composição de 14 membros; 46 tomadas de depoimento. A UnB é o caso mais sistemático de repressão universitária do acervo: intervenção militar já nos primeiros dias após o golpe (primeira invasão policial-militar); expurgo de grande parte do corpo docente; prisões arbitrárias e torturas; desaparecimento de três membros identificados — Paulo de Tarso Celestino da Silva (1944–1971), Honestino Monteiro Guimarães (1947–1973) e Ieda Santos Delgado (1945–1974). Documenta o Fundo ASI-UnB (62.328 folhas, sob guarda do COREG/Arquivo Nacional), a espionagem sistemática via AAE/ApAE/AESI/ASI, o controle ideológico de contratações e a aplicação do Decreto-Lei 477. Estrutura em duas partes: Parte I — cronologia 1962–1988; Parte II — eixos temáticos e recomendações. ALERTA DE USO: o relatório tem perímetro ampliado (1964–1988); os desaparecimentos de Honestino Guimarães e Ieda Santos Delgado constam também na CNV Vol. III e no CEMDP — cruzar obrigatoriamente antes de tratar como dado novo. Perspectiva classista: documenta a perseguição ao POLOP, à ALN, à AP e ao PCdoB e o vínculo entre movimentos estudantil e operário. Proveniência: DHnet redistribui o PDF original sem alterações.",
 "cuv-es-ufes": "Relatório Final da Comissão da Verdade da Universidade Federal do Espírito Santo (CVUfes), publicado em Vitória, 2016. A comissão foi instituída pela Portaria nº 478, de 27 de fevereiro de 2013, por iniciativa da Reitoria (da então vice-reitora, professora Maria Aparecida Santos Corrêa Barreto, falecida em setembro de 2013, antes da conclusão). Composição de 10 membros (docentes, técnico-administrativos, discentes); parceria com a Comissão de Anistia do MJ e o Projeto Memórias Reveladas/Arquivo Nacional. O relatório estrutura a repressão em quatro 'ondas': (1) O Golpe e a Universidade (1964); (2) A Ditadura se Fecha (AI-5, 1968–); (3) Graves Violações dos Direitos Humanos no Espírito Santo; (4) A Universidade sob o Olhar da Repressão Política (1975–1985). Apura violações contra estudantes, docentes e técnico-administrativos; documenta o funcionamento da AESI na Ufes (1971–1986) e pesquisa seu acervo; registra exonerações, aposentadorias forçadas e expulsões. O ES tem contexto industrial (CST, Samarco) e de trabalhadores rurais e urbanos que se entrelaça com a repressão universitária. COMPLEMENTARIDADE: este relatório complementa a Comissão Estadual da Memória e Verdade Orlando Bomfim (Cemvob-ES), ainda não ingerida — sem sobreposição direta: a CVUfes foca a instituição universitária. Proveniência: DHnet redistribui o PDF original sem alterações.",
 "cuv-mg-ufop": "Relatório Final do Grupo de Trabalho da Universidade Federal de Ouro Preto (GT UFOP), publicado em Ouro Preto, dezembro de 2017. O GT foi formado por termo de cooperação firmado em outubro de 2016 entre a UFOP e a Comissão da Verdade em Minas Gerais (Covemg), com trabalho de campo entre novembro de 2016 e julho de 2017. Escopo declarado: violações de direitos fundamentais na comunidade universitária de Ouro Preto e na cidade, de 1946 a 1988, com foco no pós-1964 e no movimento estudantil das Escolas de Minas (EMOP) e de Farmácia (EFAR), preexistentes à UFOP (criada em 1969). Documenta a Operação Limpeza (1964), a repressão nas comemorações do 21 de abril, as repúblicas estudantis como focos de resistência, prisões e torturas de estudantes (casos individuais: Dietrich Sebald Ritter Von Kostrich, Rogério Peret Teixeira, João Francisco Castelão Júnior, Newton Moraes), o enquadramento no Decreto-Lei 477, a ASI/UFOP e o monitoramento de docentes. A Parte I reconstitui o contexto político de Ouro Preto, articulando as disputas de classe nas estruturas oligárquicas mineiras. ALERTA DE USO: (a) o GT declara que a pesquisa voltou-se primordialmente ao movimento estudantil — casos de docentes e funcionários são introdutórios e demandam aprofundamento; (b) NÃO confundir com o relatório principal da Covemg (cev-mg-covemg-relatorio-final-2017) nem com o do Triângulo Mineiro (cev-mg-triangulo-mineiro); (c) os anexos integram o documento e foram chunkados junto. Proveniência: DHnet redistribui o PDF original sem alterações.",
 "cuv-pb-ufcg": "ATENÇÃO — RELATÓRIO PARCIAL. Relatório Parcial das Atividades da Comissão da Verdade, da Memória e da Justiça das Entidades Representativas da Universidade Federal de Campina Grande (CVMJER/UFCG), publicado em março de 2015, referente a fevereiro de 2014 a fevereiro de 2015. É prestação de contas de um ano de trabalho, não relatório final: as investigações estavam em andamento e os resultados são explicitamente preliminares. DISTINÇÃO INSTITUCIONAL: a comissão não foi criada pela administração da UFCG, mas pelas entidades representativas (ADUFCG, ADUC, ADUFCG-Patos, SINTESPB/UFCG, DCE/UFCG), em deliberação do II Congresso Universitário — caráter político-sindical explícito, distinto das comissões criadas por portaria reitoral, sem que isso desqualifique sua validade como fonte. A UFCG foi desmembrada da UFPB em 2002; o relatório investiga os campi que lhe deram origem (Campina Grande, Patos, Sousa, Cajazeiras, Bananeiras), então parte da UFPB. Registra 33 depoimentos (maioria de ex-alunos), pesquisa em arquivos (ASODS/UFPB, AGUFCG, DOPS-PB, comissão estadual da PB), e análise do movimento estudantil pré-1964 (crise da renúncia de Jânio em 1961, mobilização contra a visita de Carlos Lacerda em março de 1964, intervenção federal que destituiu o reitor eleito e nomeou o capitão Guilardo Martins Alves, punição de 11 estudantes pela Resolução nº 18/1964 do Consuni da UFPB). Contexto regional relevante: a Paraíba das Ligas Camponesas, de João Pedro Teixeira e Margarida Maria Alves — a repressão universitária não se desconecta da violência contra trabalhadores rurais, intersecção de classe explícita na apresentação. ALERTA DE USO: (a) documento PARCIAL — informações factuais individuais devem ser cotejadas com fontes complementares; (b) o relatório final, se produzido, não está no acervo; (c) investiga os campi da antiga UFPB no interior, não a UFPB de João Pessoa (sede), de história institucional distinta — não confundir com cmv-pb-joao-pessoa. Proveniência: DHnet redistribui o PDF original sem alterações.",
 "cuv-sp-unicamp": "Relatório Final da Comissão da Verdade e Memória 'Octávio Ianni' da Universidade Estadual de Campinas (Unicamp), publicado em Campinas, 1º de abril de 2015. Criada pela Portaria GR-111, de 20 de setembro de 2013. O nome homenageia Octávio Ianni, sociólogo marxista, docente da Unicamp e um dos intelectuais mais perseguidos pelo regime. Composição de 6 membros titulares (IFCH e IE) e suplentes. A Unicamp, universidade estadual paulista fundada em 1966 durante a ditadura, tem história institucional inicial inseparável do contexto autoritário. O relatório enfrenta diretamente a narrativa de que a Unicamp 'teria ficado ao largo da ditadura', atribuída ao reitor fundador Zeferino Vaz — que forneceu peruas ao Exército nos dias do golpe e denunciou intelectuais marxistas, mas protegeu seletivamente alguns docentes. Documenta: a prisão e tortura do docente Ademir Gebara na OBAN (1975); prisões e torturas de estudantes nos anos 1970; Alcides Mamizuka, dois anos preso pela LSN; ameaças de morte a jovens docentes (incluindo Luiz Gonzaga Belluzzo, que deixou o país); e o título Doutor Honoris Causa concedido em 1973 ao coronel Jarbas Passarinho, cuja revogação o Consu não aprovou em 2014. Sistematiza depoimentos de 14 pessoas, linha do tempo e recomendações. ALERTA DE USO: relatório breve (61 p.) e centrado em depoimentos, não exaustivo; a Unicamp é estadual (governo de SP), com dinâmica repressiva própria, distinta da incidência direta da AESI/DSI/MEC sobre as federais. Proveniência: DHnet redistribui o PDF original sem alterações.",
 "cuv-sp-unifesp": "INFORME (versão reduzida) sobre o Relatório Final da Comissão da Verdade 'Marcos Lindenberg' da Universidade Federal de São Paulo (UNIFESP), 2015. ATENÇÃO À NATUREZA DO DOCUMENTO: o arquivo disponível no DHnet é o Informe apresentado ao Conselho Universitário (Consu) ao fim de três anos de trabalho, com seleção de capítulos — NÃO a versão integral, que estava em preparação para publicação em livro (conforme a própria Apresentação). O relatório completo tem quatro partes e 25 biografias; o informe reproduz a Abertura, o capítulo '1972: Estudantes no Olho do Furacão', duas das 25 biografias (Cássia Maria Luperni e Luiz Carlos Aiex Alves), um depoimento (Nestor Schor) e dois textos de reflexão. O nome homenageia Marcos Lindenberg, reitor da então Escola Paulista de Medicina (EPM, hoje UNIFESP) de 1962 a 1964, deposto pela ditadura e depois Professor Emérito (2014). A EPM/UNIFESP tem especificidade de escola de medicina e hospital universitário; o capítulo-chave documenta a prisão de 11 alunos no contexto da operação contra o Movimento de Libertação Popular (Molipo). O conjunto registra mais de 50 depoimentos e 25 biografias. ALERTA DE USO CRÍTICO: (a) o documento é um INFORME (versão reduzida) — quem precisar do texto completo deve buscar a versão publicada em livro pela UNIFESP; (b) as 25 biografias completas e os demais depoimentos não estão neste arquivo; (c) o chunking reflete o informe, não o relatório final. Proveniência: DHnet redistribui o PDF original do informe sem alterações.",
 "cuv-rn-ufrn": "Relatório Final da Comissão da Verdade da Universidade Federal do Rio Grande do Norte (UFRN), publicado em Natal, 2015, pela EDUFRN (490 p.) — segundo maior documento do lote. A comissão foi instalada em sessão solene em 18 de dezembro de 2013, a partir de demanda dos próprios estudantes. Presidida pelo Prof. Carlos Roberto de Miranda Gomes (Direito Público), com sete membros e equipe de bolsistas. Estrutura em 12 capítulos temáticos de autoria individual: antecedentes históricos; arcabouço da ditadura no Brasil e no RN; ASI/UFRN como braço da repressão nas universidades; diligências para localizar o acervo da ASI; ação estudantil pré-1964 no RN; IPMs da UFRN (1964) e do Restaurante Universitário (1968); resistência e memória estudantil (1964–1985); movimento docente e criação da ADURN; expurgo de docentes; movimentação dos servidores federais; considerações finais e recomendações. Documenta o fichamento de 259 membros da comunidade universitária, prisões, torturas, expulsões e a atuação da ASI/UFRN (1970–1990), cujo acervo foi em grande parte destruído. ALERTA HISTORIOGRÁFICO: a Introdução do presidente da comissão (cap. I) faz percurso histórico amplo (de 1822 a 1964) com tom cívico-jurídico distinto do rigor analítico dos demais capítulos — o pesquisador deve distinguir esse enquadramento das análises documentadas; o capítulo IV (ASI/UFRN) é de alto valor por tratar do aparato repressivo interno com base em pesquisa de arquivo. Contexto regional: o RN tem forte mobilização estudantil e operária no pré-1964, incluindo a Insurreição Comunista de novembro de 1935 em Natal, evocada pelo documento como antecedente da paranoia anticomunista local. Proveniência: DHnet redistribui o PDF original sem alterações.",
}

# Subtipo aprovado pelo Yuri: o arquivo da UNIFESP é um informe, não o relatório integral.
SUBTIPOS = {
 "cuv-sp-unifesp": "informe",
}

# ---------------------------------------------------------------------------
# 1) Atualiza fontes.json (fonte única da verdade dos metadados editoriais)
catalogo = json.loads(CATALOGO.read_text(encoding="utf-8"))
for slug, nota in NOTAS.items():
    catalogo[slug]["fonte"]["nota_contexto"] = nota
for slug, subtipo in SUBTIPOS.items():
    catalogo[slug]["fonte"]["subtipo"] = subtipo
CATALOGO.write_text(json.dumps(catalogo, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"fontes.json atualizado ({len(NOTAS)} notas; subtipo informe -> UNIFESP).")

# ---------------------------------------------------------------------------
# 2) Aplica na tabela `fontes` do Supabase (UPDATE por url_origem)
url = os.environ.get("SUPABASE_URL")
chave = os.environ.get("SUPABASE_SERVICE_ROLE_KEY") or os.environ.get("SUPABASE_SERVICE_KEY")
if not (url and chave):
    raise SystemExit("SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY ausentes no .env.local")
sb = create_client(url, chave)

for slug, nota in NOTAS.items():
    f = catalogo[slug]["fonte"]
    patch = {"nota_contexto": nota}
    if slug in SUBTIPOS:
        patch["subtipo"] = SUBTIPOS[slug]
    r = sb.table("fontes").update(patch).eq("url_origem", f["url_origem"]).execute()
    print(f"  [{slug}] {len(r.data)} fonte(s) atualizada(s): {sorted(patch.keys())}")

print("Concluído.")
