import Link from "next/link";
import { NavegacaoComunidade } from "../../componentes/ComunidadeLayout";

export default function Regras() {
  return <main className="bc-page bc-document-page space-y-6"><NavegacaoComunidade />
    <h1 className="text-2xl font-bold">Como participar da comunidade</h1>
    <p>O fórum reúne discussões sobre respostas do chat, biografias e registros do mapa do projeto_BACURI. Qualquer pessoa pode ler. Para publicar, é necessário criar uma conta gratuita, confirmar o e-mail e escolher uma tag pública. A tag é um pseudônimo público persistente, ligado à conta com e-mail confirmado. Cada contribuição e revisão tem autoria; não há verificação da identidade civil. Nome real é opcional e o e-mail fica privado.</p>
    <section className="space-y-3"><h2 className="text-lg font-semibold">Da discussão à proposta</h2>
      <ol className="list-decimal pl-5 space-y-2"><li>No chat, escolha “Discutir esta resposta”. Confira a pergunta, o resumo, a resposta e as citações antes de confirmar a publicação. Evite publicar dados pessoais.</li><li>Comente, indique fontes ou proponha um texto alternativo com justificativa. É possível sugerir fontes externas; a aprovação como resposta de referência exige trechos verificáveis do acervo.</li><li>Avalie cada versão como “Apoio”, “Precisa de ajustes” ou “Sem fundamento”. As duas últimas opções exigem justificativa. Cada pessoa tem uma avaliação por versão, com o mesmo peso; autores não avaliam a própria proposta.</li><li>Uma nova versão preserva as anteriores e inicia outra rodada de avaliações. Sugestões de terceiros podem ser incorporadas com atribuição.</li></ol>
      <p>Uma discussão também pode partir de uma biografia ou de um registro do mapa, pelo botão “Discutir na comunidade”. Antes da publicação, confira o título, o motivo e a categoria. O projeto preserva a origem, o link e uma cópia do registro com suas fontes; essa cópia é obtida no servidor a partir do registro público, não de texto enviado pelo navegador.</p>
    </section>
    <section className="space-y-3"><h2 className="text-lg font-semibold">Curadoria e respostas de referência</h2>
      <p>Após 72 horas, versões com ao menos cinco avaliações e 60% de apoios entram na fila de curadoria. Curadores também podem encaminhar uma proposta antes, com justificativa. As avaliações organizam a prioridade de leitura; não verificam por si a exatidão histórica. A análise depende de fontes identificáveis, contexto e pareceres independentes.</p>
      <p>A decisão exige ao menos dois pareceres independentes concordantes. Havendo divergência, exige maioria absoluta dos curadores elegíveis. Autores e pessoas que tiveram comentários incorporados ficam impedidos de julgar aquela versão. A decisão sucinta é pública, junto com a discussão e os pareceres.</p>
      <p>Propostas sobre biografias e registros do mapa seguem as mesmas avaliações, impedimentos, pareceres, quóruns e recursos das demais propostas. Se aprovadas, não se tornam resposta de referência. Recebem o estado “Atualização editorial pendente” e seguem para a preparação e publicação editorial do acervo.</p>
      <p>“Resposta de referência” é uma versão editorial aprovada, com fontes, discussão e histórico de revisão. Somente quando a integração passar por avaliação independente e for ativada, versões vigentes podem ajudar o chat a organizar a resposta. Elas são consultadas junto aos trechos recuperados do acervo: não substituem a busca documental nem as citações. Cada resposta continua a indicar autor, documento, página ou trecho e link da fonte; sem base recuperada, o chat informa esse limite. Fontes alteradas ou retiradas impedem o uso até revisão. Suspensões, revogações e reativações mantêm histórico público. A referência não encerra controvérsias historiográficas documentadas nem treina o modelo.</p>
      <p>A aplicação de uma atualização aprovada ocorre no fluxo editorial do acervo. Depois de revisar e publicar o registro, a curadoria usa “Registrar conclusão editorial” para vincular a decisão pública ao registro atualizado. O chat só se beneficia do conteúdo quando o registro revisado e suas fontes passam pela indexação editorial normal; não há inclusão automática em respostas de referência.</p>
      <p>É possível recorrer de uma decisão ou moderação com justificativa. Quem participou da decisão anterior não julga o recurso.</p>
    </section>
    <section className="space-y-3"><h2 className="text-lg font-semibold">Níveis de participação</h2>
      <p>Os níveis sobem automaticamente pelo conjunto de contribuições reconhecidas, tempo de participação e dias de atividade.</p>
      <div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Três níveis de participação e critérios</caption><thead><tr><th className="p-2">Faixa</th><th className="p-2">Critério mínimo</th></tr></thead><tbody>{[["Participante", "Conta ativa"], ["Colaborador", "20 pontos · 7 dias · 3 dias ativos"], ["Colaborador experiente", "100 pontos · 30 dias · 10 dias ativos"]].map(row => <tr key={row[0]} className="border-t">{row.map((cell, i) => <td key={i} className="p-2">{cell}</td>)}</tr>)}</tbody></table></div>
      <p className="text-sm">Um comentário reconhecido por três outras contas com ao menos sete dias recebe 2 pontos; uma sugestão incorporada por outro autor, 10; uma proposta aprovada como resposta de referência, 30. Cada reconhecimento é contabilizado uma vez. Reconhecimentos da comunidade têm limite de 10 pontos por dia. Entrar na conta, votar ou publicar em volume não gera pontos. Fraudes podem invalidar pontuação, com justificativa e possibilidade de recurso.</p>
      <p>As faixas reconhecem atividade; não comprovam conhecimento histórico nem dão peso extra às avaliações. Curador é uma função editorial distinta, indicada com consentimento e aprovada por unanimidade dos curadores em atividade. Nenhuma faixa automática concede essa função. A saída é voluntária; uma destituição exige defesa ou prazo de sete dias e aprovação de dois terços dos demais curadores. O projeto preserva ao menos um curador.</p>
    </section>
    <section className="space-y-3"><h2 className="text-lg font-semibold">Compromissos e direitos</h2>
      <p>Indicar uma fonte não equivale a validá-la: documentos de órgãos repressivos, imprensa sob censura e testemunhos exigem proveniência e contexto. Fundamente afirmações, indique autor, documento e página quando disponível, trate as pessoas com respeito e não publique dados pessoais de terceiros. Tortura, mortes e desaparecimentos documentados não são tratados como opiniões equivalentes a sua negação.</p>
      <p>Ao publicar, você licencia somente o texto original que escreveu para a comunidade sob <a className="underline" href="https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0 (nova aba)</a>. Documentos, imagens, transcrições e outros materiais de terceiros conservam seus próprios direitos e condições de acesso. Publique apenas excertos necessários à discussão e a referência da fonte; não envie obra integral protegida sem autorização. O software do projeto é AGPL-3.0.</p>
      <p>Conteúdo ocultado por moderação não é republicado nas áreas públicas; a medida tem justificativa e possibilidade de recurso. Você pode editar seu perfil e encerrar sua conta. O histórico de contribuições e decisões é preservado com identificação pública substituída por “Conta encerrada”.</p>
    </section>
    <nav className="flex flex-wrap gap-4 underline"><Link href="/conta">Criar conta ou entrar</Link><Link href="/comunidade">Consultar discussões</Link><Link href="/transparencia">Transparência editorial</Link></nav>
  </main>;
}
