import Link from "next/link";
import { NavegacaoComunidade } from "../../componentes/ComunidadeLayout";

export default function Regras() {
  return <main className="bc-page bc-document-page space-y-6"><NavegacaoComunidade />
    <h1 className="text-2xl font-bold">Como participar da comunidade</h1>
    <p>O fórum reúne discussões sobre respostas do projeto_BACURI. Qualquer pessoa pode ler. Para publicar, é necessário criar uma conta gratuita, confirmar o e-mail e escolher uma tag pública. A tag é um pseudônimo público persistente, ligado à conta com e-mail confirmado. Cada contribuição e revisão tem autoria; não há verificação da identidade civil. Nome real é opcional e o e-mail fica privado.</p>
    <section className="space-y-3"><h2 className="text-lg font-semibold">Da resposta à proposta</h2>
      <ol className="list-decimal pl-5 space-y-2"><li>No chat, escolha “Discutir esta resposta”. Confira a pergunta, o resumo, a resposta e as citações antes de confirmar a publicação. Evite publicar dados pessoais.</li><li>Comente, indique fontes ou proponha um texto alternativo com justificativa. É possível sugerir fontes externas; a aprovação como resposta ouro exige trechos verificáveis do acervo.</li><li>Avalie cada versão como “Apoio”, “Precisa de ajustes” ou “Sem fundamento”. As duas últimas opções exigem justificativa. Cada pessoa tem uma avaliação por versão, com o mesmo peso; autores não avaliam a própria proposta.</li><li>Uma nova versão preserva as anteriores e inicia outra rodada de avaliações. Sugestões de terceiros podem ser incorporadas com atribuição.</li></ol>
    </section>
    <section className="space-y-3"><h2 className="text-lg font-semibold">Curadoria e respostas ouro</h2>
      <p>Após 72 horas, versões com ao menos cinco avaliações e 60% de apoios entram na fila de curadoria. Curadores também podem encaminhar uma proposta antes, com justificativa. As avaliações organizam a prioridade de leitura; não verificam por si a exatidão histórica. A análise depende de fontes identificáveis, contexto e pareceres independentes.</p>
      <p>A decisão exige ao menos dois pareceres independentes concordantes. Havendo divergência, exige maioria absoluta dos curadores elegíveis. Autores e pessoas que tiveram comentários incorporados ficam impedidos de julgar aquela versão. A decisão sucinta é pública, junto com a discussão e os pareceres.</p>
      <p>“Resposta ouro” é o nome de uma versão editorial aprovada, rastreável e revisável. Ela não substitui a consulta aos documentos nem encerra controvérsias historiográficas documentadas. Sua eventual utilização pelo chat mantém as citações históricas e não equivale a treinar o modelo. Fontes alteradas ou retiradas impedem seu uso até revisão. Suspensões, revogações e reativações mantêm histórico público.</p>
      <p>É possível recorrer de uma decisão ou moderação com justificativa. Quem participou da decisão anterior não julga o recurso.</p>
    </section>
    <section className="space-y-3"><h2 className="text-lg font-semibold">Níveis de participação</h2>
      <p>Os níveis sobem automaticamente pelo conjunto de contribuições reconhecidas, tempo de participação e dias de atividade.</p>
      <div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Critérios para os níveis automáticos</caption><thead><tr><th className="p-2">Nível</th><th className="p-2">Pontos</th><th className="p-2">Tempo mínimo</th><th className="p-2">Dias ativos</th></tr></thead><tbody>{[["Participante", "0", "Cadastro", "—"], ["Colaborador", "20", "7 dias", "3"], ["Revisor", "100", "30 dias", "10"], ["Referência", "300", "90 dias", "20"]].map(row => <tr key={row[0]} className="border-t">{row.map((cell, i) => <td key={i} className="p-2">{cell}</td>)}</tr>)}</tbody></table></div>
      <p className="text-sm">Um comentário reconhecido por três outras contas com ao menos sete dias recebe 2 pontos; uma sugestão incorporada por outro autor, 10; uma proposta aprovada como ouro, 30. Cada reconhecimento é contabilizado uma vez. Reconhecimentos da comunidade têm limite de 10 pontos por dia. Entrar na conta, votar ou publicar em volume não gera pontos. Fraudes podem invalidar pontuação, com justificativa e possibilidade de recurso.</p>
      <p>Curador é uma função editorial: exige indicação, consentimento da pessoa candidata e aprovação de todos os curadores em atividade. Nenhum nível automático concede essa função. A saída é voluntária; uma destituição exige defesa ou prazo de sete dias e aprovação de dois terços dos demais curadores. O projeto preserva ao menos um curador.</p>
    </section>
    <section className="space-y-3"><h2 className="text-lg font-semibold">Compromissos e direitos</h2>
      <p>Indicar uma fonte não equivale a validá-la: documentos de órgãos repressivos, imprensa sob censura e testemunhos exigem proveniência e contexto. Fundamente afirmações, indique autor, documento e página quando disponível, trate as pessoas com respeito e não publique dados pessoais de terceiros. Tortura, mortes e desaparecimentos documentados não são tratados como opiniões equivalentes a sua negação.</p>
      <p>Ao publicar, você licencia somente o texto original que escreveu para a comunidade sob <a className="underline" href="https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0 (nova aba)</a>. Documentos, imagens, transcrições e outros materiais de terceiros conservam seus próprios direitos e condições de acesso. Publique apenas excertos necessários à discussão e a referência da fonte; não envie obra integral protegida sem autorização. O software do projeto é AGPL-3.0.</p>
      <p>Conteúdo ocultado por moderação não é republicado nas áreas públicas; a medida tem justificativa e possibilidade de recurso. Você pode editar seu perfil e encerrar sua conta. O histórico de contribuições e decisões é preservado com identificação pública substituída por “Conta encerrada”.</p>
    </section>
    <nav className="flex flex-wrap gap-4 underline"><Link href="/conta">Criar conta ou entrar</Link><Link href="/comunidade">Consultar discussões</Link><Link href="/transparencia">Transparência editorial</Link></nav>
  </main>;
}
