"use client";

import Link from "next/link";
import ProgressoQuorum from "../../componentes/ProgressoQuorum";
import type { Quorum } from "@/lib/server/quorum-comunidade";
import { NavegacaoComunidade } from "../../componentes/ComunidadeLayout";
import { useEffect, useState } from "react";
import { comunidadeGet, comunidadePost, MensagemErro, nomeAutor, type Autor } from "../../componentes/ComunidadeApi";
import { BotaoAcao, FontesProposta, FormularioAcao, type FonteComunidade } from "../../componentes/DiscussaoFormularios";

type Proposta = { origem?: string; proposta_id: string; discussao_id: string; titulo: string; autor: Autor; impedido: boolean; quorum?: Quorum; versao: { versao_id: string; numero: number; texto: string; justificativa: string; fontes: FonteComunidade[]; fontes_sugeridas: string; estado: string; apoios: number; ajustes: number; sem_fundamento: number; ciclo?: number; pareceres?: { autor: Autor; ciclo: number }[] } };
type Alvo = { alvo_tipo: "discussao" | "comentario" | "proposta" | "membro"; alvo_id: string; discussao_id?: string };
type Painel = { editoriais?: { decisao_id: string; discussao_id: string; versao_id: string; titulo: string; origem_link: string; impedido: boolean }[]; itens: Proposta[]; curadores: { user_id: string; nome: string; ativo: boolean }[]; candidaturas: { candidatura_id: string; candidato: Autor; consentido_em: string | null; votos: { curador_id: string; aprova: boolean }[] | null; quorum?: Quorum }[]; destituicoes: { destituicao_id: string; alvo_id: string; justificativa: string; defesa: string | null; quorum?: Quorum }[]; denuncias: (Alvo & { denuncia_id: string; motivo: string })[]; moderacoes: (Alvo & { moderacao_id: string; acao: string; justificativa: string })[]; recursos: { recurso_id: string; alvo_tipo: string; alvo_id: string; motivo: string; quorum?: Quorum }[] };
type Ouro = { ouro_id: string; versao_id: string; discussao_id: string; titulo: string; estado: string; fontes_validas: boolean };

function Parecer({ proposta: p, impedidoPorRecurso = false, concluido }: { proposta: Proposta; impedidoPorRecurso?: boolean; concluido: () => void }) {
  const [resultado, setResultado] = useState("ajustes"); const [justificativa, setJustificativa] = useState(""); const [sintese, setSintese] = useState(""); const [erro, setErro] = useState(""); const [aviso, setAviso] = useState(""); const [enviando, setEnviando] = useState(false);
  if (impedidoPorRecurso) return <p className="mt-3 text-sm">Você participou de uma rodada anterior. Este recurso exige pareceristas independentes.</p>;
  if (p.impedido || p.quorum?.impedido) return <p className="mt-3 text-sm">Você está impedido de julgar esta proposta por participação na autoria.</p>;
  if (p.versao.estado === "aberta") return <p className="mt-3 text-sm">Esta versão aguarda encaminhamento. Se houve pedido de ajustes, o autor precisa publicar uma nova versão.</p>;
  return <form className="mt-4 space-y-3" onSubmit={async e => { e.preventDefault(); setErro(""); setEnviando(true); try { const r = await comunidadePost("parecer", { versao_id: p.versao.versao_id, resultado, justificativa, sintese }); setAviso(r.resultado?.estado_editorial === "pendente" ? "Decisão registrada. Atualização editorial pendente." : r.indexacao_pendente ? "Decisão registrada; indexação pendente. Use a retentativa no painel de ouro." : "Parecer registrado. A decisão aguarda o quórum quando necessário."); concluido(); } catch (x) { setErro(x instanceof Error ? x.message : "Não foi possível registrar."); } finally { setEnviando(false); } }}>
    <label className="block text-sm">Resultado<select aria-label="Resultado" value={resultado} onChange={e => setResultado(e.target.value)} className="mt-1 rounded border p-2"><option value="aprovar">Aprovar</option><option value="recusar">Recusar</option><option value="ajustes">Pedir ajustes</option></select></label>
    <label className="block text-sm">Justificativa do parecer<textarea required minLength={10} maxLength={3000} value={justificativa} onChange={e => setJustificativa(e.target.value)} className="mt-1 block w-full rounded border p-2" /></label>
    <label className="block text-sm">Síntese pública da decisão<textarea required minLength={10} maxLength={1200} value={sintese} onChange={e => setSintese(e.target.value)} className="mt-1 block w-full rounded border p-2" /></label>
    <button className="bk-button" disabled={enviando || (resultado === "aprovar" && !p.versao.fontes.length)}>Registrar parecer</button>{!p.versao.fontes.length && <p className="text-xs">A aprovação exige fontes vinculadas ao acervo.</p>}{erro && <MensagemErro erro={erro} />}{aviso && <p role="status" className="text-sm">{aviso}</p>}
  </form>;
}
function Moderacao({ alvo, concluido }: { alvo: Alvo; concluido: () => void }) {
  const [acao, setAcao] = useState(alvo.alvo_tipo === "membro" ? "suspender_membro" : "ocultar");
  const opcoes = alvo.alvo_tipo === "membro" ? [["suspender_membro", "Suspender participação"], ["restaurar_membro", "Restaurar participação"], ["invalidar_pontos", "Invalidar pontos fraudulentos"]] : [["ocultar", "Ocultar conteúdo"], ["restaurar", "Restaurar conteúdo"], ["invalidar_pontos", "Invalidar pontos fraudulentos"]];
  return <><label className="mt-3 block text-sm">Ação de moderação<select aria-label="Ação de moderação" value={acao} onChange={e => setAcao(e.target.value)} className="mt-1 rounded border p-2">{opcoes.map(([v, t]) => <option key={v} value={v}>{t}</option>)}</select></label><FormularioAcao acao="moderar" base={{ alvo_tipo: alvo.alvo_tipo, alvo_id: alvo.alvo_id, acao }} campo="justificativa" maximo={2000} rotulo="Justificativa da moderação" botao="Registrar moderação" concluido={concluido} /></>;
}
function Indicacao({ concluido }: { concluido: () => void }) {
  const [tag, setTag] = useState(""); const [erro, setErro] = useState(""); const [enviando, setEnviando] = useState(false);
  return <form className="mt-3 space-y-3" onSubmit={async e => { e.preventDefault(); setErro(""); setEnviando(true); try { const p: { user_id: string } = await comunidadeGet("perfil", { tag: tag.toLowerCase() }); await comunidadePost("candidatar", { candidato_id: p.user_id }); concluido(); } catch (x) { setErro(x instanceof Error ? x.message : "Não foi possível indicar."); } finally { setEnviando(false); } }}><label className="block text-sm">Tag da pessoa indicada<input required pattern="@[a-z0-9_]{3,30}" value={tag} onChange={e => setTag(e.target.value)} className="mt-1 block w-full rounded border p-2" /></label><button className="bk-button" disabled={enviando}>Indicar pessoa</button>{erro && <MensagemErro erro={erro} />}</form>;
}
function Recurso({ item: r, concluido }: { item: Painel["recursos"][number]; concluido: () => void }) {
  const [aprova, setAprova] = useState(false);
  return <article className="bk-card mt-3"><p className="text-sm whitespace-pre-wrap">{r.motivo}</p><ProgressoQuorum quorum={r.quorum} rotulosVotos={["pela reversão", "pela manutenção"]} />{r.alvo_tipo === "decisao" ? <p className="mt-3 text-sm">Recurso editorial: confira a versão recorrida na fila de propostas. Os pareceristas anteriores estão impedidos.</p> : r.quorum?.impedido ? <p className="mt-3 text-sm">Este recurso exige revisão independente. Você não pode emitir parecer.</p> : <><label className="mt-3 block text-sm">Parecer sobre o recurso<select aria-label="Parecer sobre o recurso" value={String(aprova)} onChange={e => setAprova(e.target.value === "true")} className="mt-1 rounded border p-2"><option value="false">Manter a moderação</option><option value="true">Reverter a moderação</option></select></label><FormularioAcao acao="parecer_recurso" base={{ recurso_id: r.recurso_id, aprova }} campo="justificativa" rotulo="Justificativa do parecer independente" botao="Registrar parecer sobre recurso" concluido={concluido} /></>}</article>;
}
export default function Curadoria() {
  const [painel, setPainel] = useState<Painel>(); const [ouro, setOuro] = useState<Ouro[]>([]); const [userId, setUserId] = useState(""); const [minhaTag, setMinhaTag] = useState(""); const [erro, setErro] = useState(""); const [pagina, setPagina] = useState(1); const [revisao, setRevisao] = useState(0); const [carregando, setCarregando] = useState(true); const [alvoDestituicao, setAlvoDestituicao] = useState(""); const [saida, setSaida] = useState(false);
  const atualizar = () => { window.dispatchEvent(new Event("bacuri-perfil-atualizado")); setRevisao(r => r + 1); };
  useEffect(() => {
    let ativo = true;
    async function carregar() {
      setCarregando(true); setErro("");
      try { const [p, o, eu] = await Promise.all([comunidadeGet("curadoria", { pagina: String(pagina) }), comunidadeGet("ouro", { pagina: String(pagina) }), comunidadeGet("eu")]); if (ativo) { setPainel(p); setOuro(o.itens || []); setUserId(eu.user_id); setMinhaTag(eu.perfil ? nomeAutor(eu.perfil.tag) : ""); } }
      catch (e) { if (ativo) setErro(e instanceof Error ? e.message : "Não foi possível carregar o painel."); }
      finally { if (ativo) setCarregando(false); }
    }
    void carregar(); return () => { ativo = false; };
  }, [pagina, revisao]);
  const nomeCurador = (id: string) => painel?.curadores.find(c => c.user_id === id)?.nome || "Curador(a)";
  return <main className="bc-page bc-document-page bc-curation-page"><NavegacaoComunidade /><h1 className="text-2xl font-bold">Painel de curadoria</h1><p className="mt-2 text-sm">Confira versão, fontes e contexto antes de emitir parecer. Autores e colaboradores ficam impedidos; as decisões são públicas e exigem quórum.</p><Link className="mt-3 inline-block text-sm underline" href="/comunidade">Voltar à comunidade</Link>
    {erro && <div className="mt-4"><MensagemErro erro={erro} /></div>}{carregando && <p role="status" className="mt-4">Atualizando painel…</p>}
    {!erro && painel && <>
      <section className="mt-7"><h2 className="text-lg font-semibold">Propostas para análise</h2>{!painel.itens.length && <p className="mt-3 text-sm">Nenhuma proposta nesta página.</p>}{painel.itens.map(p => <article key={p.proposta_id} className="bk-card mt-4"><h3 className="font-semibold">{p.titulo}</h3><p className="mt-2 text-xs">{nomeAutor(p.autor)} · versão {p.versao.numero} · {p.versao.estado} · {p.versao.apoios} apoios, {p.versao.ajustes} ajustes, {p.versao.sem_fundamento} sem fundamento</p><p className="mt-3 text-sm whitespace-pre-wrap">{p.versao.texto}</p><p className="mt-3 text-sm whitespace-pre-wrap"><strong>Justificativa: </strong>{p.versao.justificativa}</p>{p.versao.fontes_sugeridas && <p className="mt-3 text-sm whitespace-pre-wrap">Fontes externas sugeridas: {p.versao.fontes_sugeridas}</p>}{!!p.versao.fontes.length && <FontesProposta fontes={p.versao.fontes} />}<Link className="mt-3 inline-block text-sm underline" href={`/comunidade/${p.discussao_id}#${p.proposta_id}`}>Consultar discussão e histórico</Link><ProgressoQuorum quorum={p.quorum} /><details className="bc-curation-review"><summary>Emitir parecer</summary><Parecer proposta={p} impedidoPorRecurso={p.versao.estado === "recorrida" && !!p.versao.pareceres?.some(pc => nomeAutor(pc.autor) === minhaTag && pc.ciclo < (p.versao.ciclo || 1))} concluido={atualizar} /></details>{p.versao.estado === "aberta" && <details className="mt-3"><summary className="text-sm">Encaminhar excepcionalmente</summary><FormularioAcao acao="encaminhar" base={{ versao_id: p.versao.versao_id }} campo="justificativa" rotulo="Justificativa do encaminhamento" concluido={atualizar} /></details>}</article>)}</section>
      <section className="mt-8"><h2 className="text-lg font-semibold">Atualizações editoriais pendentes</h2><p className="mt-2 text-sm">Revise e publique o registro pelo fluxo editorial do acervo. Depois, registre a conclusão com uma justificativa pública.</p>{!painel.editoriais?.length && <p className="mt-3 text-sm">Nenhuma atualização pendente nesta página.</p>}{painel.editoriais?.map(d => <article className="bk-card mt-3" key={d.decisao_id}><h3>{d.titulo}</h3><div className="mt-2 flex flex-wrap gap-4 text-sm underline"><Link href={`/comunidade/${d.discussao_id}?versao_id=${d.versao_id}#${d.versao_id}`}>Consultar decisão pública</Link><Link href={d.origem_link}>Consultar registro</Link></div>{d.impedido ? <p className="mt-3 text-sm">A conclusão exige um curador independente da autoria da proposta.</p> : <FormularioAcao acao="concluir_editorial" base={{ decisao_id: d.decisao_id }} campo="justificativa" rotulo="Justificativa da conclusão editorial" botao="Registrar conclusão editorial" concluido={atualizar} />}</article>)}</section>
      <section className="mt-8"><h2 className="text-lg font-semibold">Candidaturas à curadoria</h2><p className="mt-2 text-sm">A admissão exige consentimento e aprovação expressa de todos os curadores em atividade.</p><Indicacao concluido={atualizar} />{painel.candidaturas.map(c => <article className="bk-card mt-3" key={c.candidatura_id}><p>{nomeAutor(c.candidato)} · {c.consentido_em ? "Consentimento registrado" : "Aguardando consentimento"}</p><ProgressoQuorum quorum={c.quorum} tipo="unanimidade" /><ul className="mt-2 text-xs">{c.votos?.map(v => <li key={v.curador_id}>{nomeCurador(v.curador_id)}: {v.aprova ? "Aprova" : "Não aprova"}</li>)}</ul><div className="mt-3 flex flex-wrap gap-4"><BotaoAcao acao="votar_candidatura" dados={{ candidatura_id: c.candidatura_id, aprova: true }} concluido={atualizar}>Aprovar candidatura</BotaoAcao><BotaoAcao acao="votar_candidatura" dados={{ candidatura_id: c.candidatura_id, aprova: false }} concluido={atualizar}>Não aprovar candidatura</BotaoAcao></div></article>)}</section>
      <section className="mt-8"><h2 className="text-lg font-semibold">Denúncias e moderação</h2>{!painel.denuncias.length && <p className="mt-3 text-sm">Nenhuma denúncia pendente.</p>}{painel.denuncias.map(d => <article className="bk-card mt-3" key={d.denuncia_id}><p className="text-sm whitespace-pre-wrap">{d.motivo}</p><p className="mt-2 text-xs">Alvo: {d.alvo_tipo} · {d.alvo_id}</p>{d.discussao_id && <Link className="text-sm underline" href={`/comunidade/${d.discussao_id}${d.alvo_tipo === "discussao" ? "" : `#${d.alvo_id}`}`}>Consultar conteúdo denunciado</Link>}<Moderacao alvo={{ alvo_tipo: d.alvo_tipo, alvo_id: d.alvo_id }} concluido={atualizar} /></article>)}<details className="mt-4"><summary>Histórico de moderação e restauração</summary>{painel.moderacoes.map(m => <article className="bk-card mt-3" key={m.moderacao_id}><p className="text-sm">{m.acao}: {m.justificativa}</p><Moderacao alvo={{ alvo_tipo: m.alvo_tipo, alvo_id: m.alvo_id }} concluido={atualizar} /></article>)}</details></section>
      <section className="mt-8"><h2 className="text-lg font-semibold">Recursos</h2>{!painel.recursos.length && <p className="mt-3 text-sm">Nenhum recurso pendente.</p>}{painel.recursos.map(r => <Recurso key={r.recurso_id} item={r} concluido={atualizar} />)}</section>
      <section className="mt-8"><h2 className="text-lg font-semibold">Composição da curadoria</h2><ul className="mt-3 text-sm">{painel.curadores.filter(c => c.ativo).map(c => <li key={c.user_id}>{c.nome}</li>)}</ul><details className="mt-4"><summary>Propor destituição</summary><label className="mt-3 block text-sm">Curador(a)<select aria-label="Curador(a)" value={alvoDestituicao} onChange={e => setAlvoDestituicao(e.target.value)} className="mt-1 rounded border p-2"><option value="">Selecione</option>{painel.curadores.filter(c => c.ativo && c.user_id !== userId).map(c => <option key={c.user_id} value={c.user_id}>{c.nome}</option>)}</select></label>{alvoDestituicao && <FormularioAcao acao="propor_destituicao" base={{ alvo_id: alvoDestituicao }} campo="justificativa" rotulo="Justificativa da proposta" concluido={atualizar} />}</details>{painel.destituicoes.filter(d => painel.curadores.some(c => c.user_id === d.alvo_id && c.ativo)).map(d => <article className="bk-card mt-3" key={d.destituicao_id}><h3 className="font-semibold">Procedimento: {nomeCurador(d.alvo_id)}</h3><p className="mt-2 text-sm">{d.justificativa}</p><ProgressoQuorum quorum={d.quorum} tipo="destituicao" />{d.defesa && <p className="mt-3 text-sm whitespace-pre-wrap"><strong>Defesa: </strong>{d.defesa}</p>}{d.alvo_id === userId ? <FormularioAcao acao="defender_destituicao" base={{ destituicao_id: d.destituicao_id }} campo="defesa" rotulo="Sua defesa" concluido={atualizar} /> : <div className="mt-3 flex flex-wrap gap-4"><BotaoAcao acao="votar_destituicao" dados={{ destituicao_id: d.destituicao_id, aprova: true }} concluido={atualizar}>Votar pela destituição</BotaoAcao><BotaoAcao acao="votar_destituicao" dados={{ destituicao_id: d.destituicao_id, aprova: false }} concluido={atualizar}>Votar contra a destituição</BotaoAcao></div>}</article>)}</section>
      <section className="mt-8"><h2 className="text-lg font-semibold">Respostas de referência</h2>{!ouro.length && <p className="mt-3 text-sm">Nenhuma resposta de referência nesta página.</p>}{ouro.map(o => <article className="bk-card mt-3" key={o.ouro_id}><h3 className="font-semibold">{o.titulo}</h3><p className="mt-2 text-xs">{o.estado}{!o.fontes_validas && " · fontes alteradas ou indisponíveis"}</p><Link className="mt-2 inline-block text-sm underline" href={`/comunidade/${o.discussao_id}`}>Conferir resposta e fontes</Link>{o.estado !== "suspensa" && <details className="mt-3"><summary className="text-sm">Suspender preventivamente</summary><FormularioAcao acao="suspender_ouro" base={{ ouro_id: o.ouro_id }} campo="justificativa" rotulo="Motivo da suspensão" concluido={atualizar} /></details>}{o.estado === "suspensa" && <><details className="mt-3"><summary className="text-sm">Emitir parecer pela reativação</summary><FormularioAcao acao="revisar_ouro" base={{ ouro_id: o.ouro_id, resultado: "reativar" }} campo="justificativa" rotulo="Justificativa da reativação" concluido={atualizar} /></details><details className="mt-3"><summary className="text-sm">Emitir parecer pela revogação</summary><FormularioAcao acao="revisar_ouro" base={{ ouro_id: o.ouro_id, resultado: "revogar" }} campo="justificativa" rotulo="Justificativa da revogação" concluido={atualizar} /></details></>}<div className="mt-3"><BotaoAcao acao="indexar_ouro" dados={{ versao_id: o.versao_id }} concluido={atualizar}>Preparar para consulta do chat</BotaoAcao></div></article>)}</section>
      <nav className="mt-7 flex justify-between" aria-label="Páginas do painel"><button disabled={pagina === 1 || carregando} onClick={() => setPagina(p => p - 1)}>Anterior</button><span>Página {pagina}</span><button disabled={carregando || (painel.itens.length < 20 && ouro.length < 20)} onClick={() => setPagina(p => p + 1)}>Próxima</button></nav>
      <details className="mt-8 border-t pt-5"><summary>Saída voluntária da curadoria</summary><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={saida} onChange={e => setSaida(e.target.checked)} />Confirmo que desejo sair do colegiado. Meus pareceres permanecem no histórico.</label><div className="mt-3"><BotaoAcao acao="sair_curadoria" dados={{ confirmacao: "SAIR" }} disabled={!saida} concluido={atualizar}>Confirmar saída da curadoria</BotaoAcao></div></details>
    </>}
  </main>;
}
