-- Fundação do fórum: tabelas privadas com RLS. RPCs são definidas na migração 0035.
create table membros_comunidade (
  user_id uuid primary key references auth.users(id) on delete cascade,
  tag text not null unique check (tag ~ '^@[a-z0-9_]{3,30}$'),
  nome_publico text check (char_length(nome_publico) <= 120), bio text check (char_length(bio) <= 500),
  pontos integer not null default 0 check (pontos >= 0), nivel text not null default 'participante' check (nivel in ('participante','colaborador','revisor','referencia')),
  suspenso_em timestamptz, criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now()
);
create table discussoes_comunidade (
  discussao_id uuid primary key default gen_random_uuid(), interacao_id uuid not null unique references interacoes(interacao_id),
  autor_id uuid not null references membros_comunidade(user_id), titulo text not null check (char_length(titulo) between 5 and 180),
  motivo text not null check (char_length(motivo) between 10 and 3000), categoria text not null check (categoria in ('erro_factual','omissao','fontes','interpretacao','clareza')),
  pergunta text not null, resumo text not null default '', resposta text not null, citacoes jsonb not null default '[]',
  oculto_em timestamptz, criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now()
);
create table comentarios_comunidade (
  comentario_id uuid primary key default gen_random_uuid(), discussao_id uuid not null references discussoes_comunidade(discussao_id) on delete cascade,
  autor_id uuid not null references membros_comunidade(user_id), pai_id uuid references comentarios_comunidade(comentario_id),
  texto text not null check (char_length(texto) between 1 and 4000), versao integer not null default 1, oculto_em timestamptz, criado_em timestamptz not null default now(), editado_em timestamptz
);
create table comentarios_revisoes (revisao_id uuid primary key default gen_random_uuid(), comentario_id uuid not null references comentarios_comunidade(comentario_id) on delete cascade, texto text not null, versao integer not null, criado_em timestamptz not null default now(), unique(comentario_id,versao));
create table reconhecimentos_comentario (comentario_id uuid not null references comentarios_comunidade(comentario_id) on delete cascade, membro_id uuid not null references membros_comunidade(user_id), criado_em timestamptz not null default now(), primary key(comentario_id,membro_id));
create table propostas_comunidade (proposta_id uuid primary key default gen_random_uuid(), discussao_id uuid not null references discussoes_comunidade(discussao_id) on delete cascade, autor_id uuid not null references membros_comunidade(user_id), proposta_origem_id uuid references propostas_comunidade(proposta_id), estado text not null default 'aberta' check(estado in ('aberta','encaminhada','decidida','oculta')), versao_atual integer not null default 1, criada_em timestamptz not null default now(), atualizada_em timestamptz not null default now());
create table propostas_versoes (versao_id uuid primary key default gen_random_uuid(), proposta_id uuid not null references propostas_comunidade(proposta_id) on delete cascade, numero integer not null, texto text not null check(char_length(texto) between 10 and 12000), justificativa text not null check(char_length(justificativa) between 10 and 4000), chunk_ids uuid[] not null check(cardinality(chunk_ids) > 0), comentario_incorporado_id uuid references comentarios_comunidade(comentario_id), estado text not null default 'aberta' check(estado in ('aberta','encaminhada','decidida','recorrida')), criada_em timestamptz not null default now(), unique(proposta_id,numero));
create table avaliacoes_proposta (versao_id uuid not null references propostas_versoes(versao_id) on delete cascade, membro_id uuid not null references membros_comunidade(user_id), tipo text not null check(tipo in ('apoio','ajustes','sem_fundamento')), justificativa text check(char_length(justificativa) between 3 and 2000), criada_em timestamptz not null default now(), atualizada_em timestamptz not null default now(), primary key(versao_id,membro_id), check((tipo='apoio' and justificativa is null) or (tipo <> 'apoio' and justificativa is not null)));
create table acompanhamentos_discussao (discussao_id uuid not null references discussoes_comunidade(discussao_id) on delete cascade, membro_id uuid not null references membros_comunidade(user_id), criado_em timestamptz not null default now(), primary key(discussao_id,membro_id));
create table notificacoes_comunidade (notificacao_id uuid primary key default gen_random_uuid(), membro_id uuid not null references membros_comunidade(user_id) on delete cascade, tipo text not null, dados jsonb not null default '{}', lida_em timestamptz, criada_em timestamptz not null default now());
create table denuncias_comunidade (denuncia_id uuid primary key default gen_random_uuid(), denunciante_id uuid not null references membros_comunidade(user_id), alvo_tipo text not null check(alvo_tipo in ('discussao','comentario','proposta','membro')), alvo_id uuid not null, motivo text not null check(char_length(motivo) between 10 and 2000), estado text not null default 'pendente' check(estado in ('pendente','resolvida')), criada_em timestamptz not null default now());
create table moderacoes_comunidade (moderacao_id uuid primary key default gen_random_uuid(), curador_id uuid not null references curadores(user_id), alvo_tipo text not null, alvo_id uuid not null, acao text not null check(acao in ('ocultar','restaurar','suspender_membro','restaurar_membro','invalidar_pontos')), justificativa text not null check(char_length(justificativa) between 10 and 2000), criada_em timestamptz not null default now());
create table recursos_comunidade (recurso_id uuid primary key default gen_random_uuid(), alvo_tipo text not null, alvo_id uuid not null, autor_id uuid not null references membros_comunidade(user_id), motivo text not null check(char_length(motivo) between 10 and 3000), estado text not null default 'pendente' check(estado in ('pendente','decidido')), criado_em timestamptz not null default now());
create table eventos_reputacao (evento_id uuid primary key default gen_random_uuid(), membro_id uuid not null references membros_comunidade(user_id), tipo text not null check(tipo in ('comentario_reconhecido','sugestao_incorporada','proposta_aprovada','reversao_fraude')), pontos integer not null, referencia_tipo text not null, referencia_id uuid not null, reverso_de uuid references eventos_reputacao(evento_id), criado_em timestamptz not null default now(), unique(membro_id,tipo,referencia_id));
create table candidaturas_curadoria (candidatura_id uuid primary key default gen_random_uuid(), candidato_id uuid not null unique references membros_comunidade(user_id), indicador_id uuid not null references curadores(user_id), consentido_em timestamptz, estado text not null default 'pendente' check(estado in ('pendente','aprovada','recusada','cancelada')), criado_em timestamptz not null default now());
create table votos_candidatura (candidatura_id uuid not null references candidaturas_curadoria(candidatura_id) on delete cascade, curador_id uuid not null references curadores(user_id), aprova boolean not null, criado_em timestamptz not null default now(), primary key(candidatura_id,curador_id));
create table destituicoes_curadoria (destituicao_id uuid primary key default gen_random_uuid(), alvo_id uuid not null references curadores(user_id), proponente_id uuid not null references curadores(user_id), justificativa text not null check(char_length(justificativa) between 10 and 3000), defesa text, estado text not null default 'pendente' check(estado in ('pendente','decidida','cancelada')), criado_em timestamptz not null default now());
create table votos_destituicao (destituicao_id uuid not null references destituicoes_curadoria(destituicao_id) on delete cascade, curador_id uuid not null references curadores(user_id), aprova boolean not null, criado_em timestamptz not null default now(), primary key(destituicao_id,curador_id));
create table pareceres_comunidade (parecer_id uuid primary key default gen_random_uuid(), versao_id uuid not null references propostas_versoes(versao_id), curador_id uuid not null references curadores(user_id), resultado text not null check(resultado in ('aprovar','recusar','ajustes')), justificativa text not null check(char_length(justificativa) between 10 and 3000), ciclo integer not null default 1, criado_em timestamptz not null default now(), unique(versao_id,curador_id,ciclo));
create table decisoes_comunidade (decisao_id uuid primary key default gen_random_uuid(), versao_id uuid not null unique references propostas_versoes(versao_id), resultado text not null check(resultado in ('aprovada','recusada')), sintese text not null check(char_length(sintese) between 10 and 1200), fontes jsonb not null default '[]', pareceristas uuid[] not null, criada_em timestamptz not null default now());
create table respostas_ouro (ouro_id uuid primary key default gen_random_uuid(), versao_id uuid not null unique references propostas_versoes(versao_id), titulo text not null check(char_length(titulo) between 5 and 180), texto text not null, chunk_ids uuid[] not null, embedding vector(384), estado text not null default 'ativa' check(estado in ('ativa','suspensa','revogada')), criada_em timestamptz not null default now(), suspensa_por uuid references curadores(user_id), motivo_suspensao text);
create table acoes_ouro (acao_id uuid primary key default gen_random_uuid(), ouro_id uuid not null references respostas_ouro(ouro_id), curador_id uuid not null references curadores(user_id), acao text not null check(acao in ('suspender','reativar','revogar')), justificativa text not null check(char_length(justificativa) between 10 and 3000), criada_em timestamptz not null default now());
create table organizacoes_comunidade (organizacao_id uuid primary key default gen_random_uuid(), membro_id uuid not null references membros_comunidade(user_id), alvo_tipo text not null, alvo_id uuid not null, acao text not null check(acao in ('etiquetar','relacionar')), dados jsonb not null default '{}', criado_em timestamptz not null default now());

create index discussoes_comunidade_lista_idx on discussoes_comunidade(criado_em desc) where oculto_em is null;
create index comentarios_comunidade_discussao_idx on comentarios_comunidade(discussao_id,criado_em) where oculto_em is null;
create index propostas_versoes_chunk_ids_idx on propostas_versoes using gin(chunk_ids);
create index notificacoes_comunidade_membro_idx on notificacoes_comunidade(membro_id,lida_em,criada_em desc);
alter table membros_comunidade enable row level security; alter table discussoes_comunidade enable row level security; alter table comentarios_comunidade enable row level security; alter table comentarios_revisoes enable row level security; alter table reconhecimentos_comentario enable row level security; alter table propostas_comunidade enable row level security; alter table propostas_versoes enable row level security; alter table avaliacoes_proposta enable row level security; alter table acompanhamentos_discussao enable row level security; alter table notificacoes_comunidade enable row level security; alter table denuncias_comunidade enable row level security; alter table moderacoes_comunidade enable row level security; alter table recursos_comunidade enable row level security; alter table eventos_reputacao enable row level security; alter table candidaturas_curadoria enable row level security; alter table votos_candidatura enable row level security; alter table destituicoes_curadoria enable row level security; alter table votos_destituicao enable row level security; alter table pareceres_comunidade enable row level security; alter table decisoes_comunidade enable row level security; alter table respostas_ouro enable row level security; alter table acoes_ouro enable row level security; alter table organizacoes_comunidade enable row level security;
