-- Projeções públicas explícitas: nenhuma leitura revela interações não compartilhadas.
create function comunidade_versao(p_versao uuid,p_ator uuid) returns jsonb language sql stable security definer set search_path=public,extensions,pg_temp as $$
 select jsonb_build_object('versao_id',v.versao_id,'numero',v.numero,'texto',v.texto,'justificativa',v.justificativa,'fontes_sugeridas',v.fontes_sugeridas,'chunk_ids',v.chunk_ids,'fontes',comunidade_fontes(v.chunk_ids),'estado',v.estado,'ciclo',v.ciclo,'criada_em',v.criada_em,
 'comentario_incorporado_id',v.comentario_incorporado_id,'apoios',(select count(*) from avaliacoes_proposta where versao_id=v.versao_id and tipo='apoio'),'ajustes',(select count(*) from avaliacoes_proposta where versao_id=v.versao_id and tipo='ajustes'),'sem_fundamento',(select count(*) from avaliacoes_proposta where versao_id=v.versao_id and tipo='sem_fundamento'),
 'minha_avaliacao',(select tipo from avaliacoes_proposta where versao_id=v.versao_id and membro_id=p_ator),
 'avaliacoes',coalesce((select jsonb_agg(jsonb_build_object('autor',comunidade_autor(a.membro_id),'tipo',a.tipo,'justificativa',a.justificativa)) from avaliacoes_proposta a where a.versao_id=v.versao_id),'[]'),
 'pareceres',coalesce((select jsonb_agg(jsonb_build_object('autor',coalesce(comunidade_autor(pc.curador_id),c.nome),'resultado',pc.resultado,'justificativa',pc.justificativa,'ciclo',pc.ciclo,'fontes_validas',pc.hashes_fontes=comunidade_hashes(v.chunk_ids))) from pareceres_comunidade pc join curadores c on c.user_id=pc.curador_id where pc.versao_id=v.versao_id),'[]'),
 'decisoes',coalesce((select jsonb_agg(jsonb_build_object('decisao_id',dc.decisao_id,'resultado',dc.resultado,'sintese',dc.sintese,'criada_em',dc.criada_em,'ciclo',dc.ciclo)) from decisoes_comunidade dc where dc.versao_id=v.versao_id),'[]'))
 from propostas_versoes v join propostas_comunidade p using(proposta_id) where v.versao_id=p_versao and p.estado<>'oculta' and comunidade_visivel(p.discussao_id)
$$;
create function comunidade_consultar(p_recurso text,p_dados jsonb,p_ator uuid default null) returns jsonb language plpgsql security definer set search_path=public,extensions,pg_temp as $$
declare itens jsonb; objeto jsonb; total integer; pagina integer:=greatest(1,least(coalesce((p_dados->>'pagina')::integer,1),10000)); inicio integer; detalhe discussoes_comunidade%rowtype; tag_n text;
begin
 inicio:=(pagina-1)*20;
 if p_recurso in ('eu','notificacoes','curadoria') and (p_ator is null or not exists(select 1 from auth.users where id=p_ator and email_confirmed_at is not null)) then raise exception 'NAO_PERMITIDO'; end if;
 if p_recurso='curadoria' and not comunidade_e_curador(p_ator) then raise exception 'NAO_PERMITIDO'; end if;
 if p_recurso='discussoes' then
  select count(*) into total from discussoes_comunidade d where d.oculto_em is null and (coalesce(p_dados->>'q','')='' or d.titulo ilike '%'||(p_dados->>'q')||'%') and (coalesce(p_dados->>'categoria','')='' or d.categoria=p_dados->>'categoria');
  select coalesce(jsonb_agg(x.item),'[]') into itens from (select jsonb_build_object('discussao_id',d.discussao_id,'titulo',d.titulo,'motivo',d.motivo,'categoria',d.categoria,'autor',comunidade_autor(d.autor_id),'criado_em',d.criado_em,'comentarios',(select count(*) from comentarios_comunidade c where c.discussao_id=d.discussao_id and c.oculto_em is null),'propostas',(select count(*) from propostas_comunidade p where p.discussao_id=d.discussao_id and p.estado<>'oculta')) item from discussoes_comunidade d
   where d.oculto_em is null and (coalesce(p_dados->>'q','')='' or d.titulo ilike '%'||(p_dados->>'q')||'%') and (coalesce(p_dados->>'categoria','')='' or d.categoria=p_dados->>'categoria')
   order by case when p_dados->>'ordem'='sem_resposta' then (select count(*) from comentarios_comunidade c where c.discussao_id=d.discussao_id and c.oculto_em is null) end asc,
   case when p_dados->>'ordem'='avaliadas' then (select coalesce(sum(case when a.tipo='apoio' then 1 else -1 end),0) from avaliacoes_proposta a join propostas_versoes v using(versao_id) join propostas_comunidade p using(proposta_id) where p.discussao_id=d.discussao_id and p.estado<>'oculta' and v.numero=p.versao_atual) end desc,d.criado_em desc limit 20 offset inicio) x;
 elsif p_recurso='discussao' then
  select * into detalhe from discussoes_comunidade where discussao_id=(p_dados->>'id')::uuid and oculto_em is null; if not found then raise exception 'AUSENTE'; end if;
  objeto:=jsonb_build_object('discussao_id',detalhe.discussao_id,'titulo',detalhe.titulo,'motivo',detalhe.motivo,'categoria',detalhe.categoria,'autor',comunidade_autor(detalhe.autor_id),'autor_id',detalhe.autor_id,'pergunta',detalhe.pergunta,'resumo',detalhe.resumo,'resposta',detalhe.resposta,'citacoes',detalhe.citacoes,'criado_em',detalhe.criado_em,'acompanhando',exists(select 1 from acompanhamentos_discussao where discussao_id=detalhe.discussao_id and membro_id=p_ator),
   'comentarios',coalesce((select jsonb_agg(x.item) from (select jsonb_build_object('comentario_id',c.comentario_id,'autor',comunidade_autor(c.autor_id),'autor_id',c.autor_id,'texto',c.texto,'pai_id',c.pai_id,'versao',c.versao,'editado_em',c.editado_em,'criado_em',c.criado_em,'revisoes',coalesce((select jsonb_agg(jsonb_build_object('texto',r.texto,'versao',r.versao)) from comentarios_revisoes r where r.comentario_id=c.comentario_id),'[]')) item from comentarios_comunidade c where c.discussao_id=detalhe.discussao_id and c.oculto_em is null and (c.pai_id is null or exists(select 1 from comentarios_comunidade cp where cp.comentario_id=c.pai_id and cp.oculto_em is null)) order by c.criado_em limit 20 offset inicio) x),'[]'),
   'total_comentarios',(select count(*) from comentarios_comunidade c where c.discussao_id=detalhe.discussao_id and c.oculto_em is null and (c.pai_id is null or exists(select 1 from comentarios_comunidade cp where cp.comentario_id=c.pai_id and cp.oculto_em is null))),
   'propostas',coalesce((select jsonb_agg(x.item) from (select jsonb_build_object('proposta_id',p.proposta_id,'autor',comunidade_autor(p.autor_id),'autor_id',p.autor_id,'estado',p.estado,'versao_atual',p.versao_atual,'proposta_origem_id',p.proposta_origem_id,'versoes',(select jsonb_agg(comunidade_versao(v.versao_id,p_ator) order by v.numero desc) from propostas_versoes v where v.proposta_id=p.proposta_id)) item from propostas_comunidade p where p.discussao_id=detalhe.discussao_id and p.estado<>'oculta' and (p_dados->>'versao_id' is null or exists(select 1 from propostas_versoes pv where pv.proposta_id=p.proposta_id and pv.versao_id=(p_dados->>'versao_id')::uuid)) order by p.criada_em limit 20 offset inicio) x),'[]'),
   'total_propostas',(select count(*) from propostas_comunidade p where p.discussao_id=detalhe.discussao_id and p.estado<>'oculta' and (p_dados->>'versao_id' is null or exists(select 1 from propostas_versoes pv where pv.proposta_id=p.proposta_id and pv.versao_id=(p_dados->>'versao_id')::uuid))),
   'organizacao',coalesce((select jsonb_agg(jsonb_build_object('acao',o.acao,'dados',o.dados,'autor',comunidade_autor(o.membro_id),'criado_em',o.criado_em)) from organizacoes_comunidade o where o.alvo_id=detalhe.discussao_id),'[]'));
  return objeto;
 elsif p_recurso in ('perfil','eu') then
  if p_recurso='eu' then perform comunidade_recalcular_nivel(p_ator); end if;
  select jsonb_build_object('user_id',m.user_id,'tag',comunidade_autor(m.user_id),'nome_publico',m.nome_publico,'bio',m.bio,'nivel',m.nivel,'pontos',m.pontos,'criado_em',m.criado_em,'suspenso',m.suspenso_em is not null,'curador',comunidade_e_curador(m.user_id)) into objeto from membros_comunidade m where m.encerrado_em is null and case when p_recurso='eu' then m.user_id=p_ator else m.tag=p_dados->>'tag' end;
  if p_recurso='eu' then
   return jsonb_build_object('perfil',objeto,'user_id',p_ator,'curador',comunidade_e_curador(p_ator),'extrato',coalesce((select jsonb_agg(jsonb_build_object('tipo',x.tipo,'pontos',x.pontos,'criado_em',x.criado_em)) from (select * from eventos_reputacao where membro_id=p_ator order by criado_em desc limit 20) x),'[]'),'candidaturas',coalesce((select jsonb_agg(jsonb_build_object('candidatura_id',c.candidatura_id,'estado',c.estado,'consentido_em',c.consentido_em)) from candidaturas_curadoria c where candidato_id=p_ator),'[]'),'moderacoes',coalesce((select jsonb_agg(jsonb_build_object('moderacao_id',mc.moderacao_id,'acao',mc.acao,'justificativa',mc.justificativa)) from moderacoes_comunidade mc where mc.alvo_id=p_ator or exists(select 1 from comentarios_comunidade cc where cc.comentario_id=mc.alvo_id and cc.autor_id=p_ator) or exists(select 1 from propostas_comunidade pp where pp.proposta_id=mc.alvo_id and pp.autor_id=p_ator) or exists(select 1 from discussoes_comunidade dd where dd.discussao_id=mc.alvo_id and dd.autor_id=p_ator)),'[]'));
  end if;
  if objeto is null then raise exception 'AUSENTE'; end if;
  return objeto||jsonb_build_object('contribuicoes',coalesce((select jsonb_agg(jsonb_build_object('discussao_id',d.discussao_id,'titulo',d.titulo)) from discussoes_comunidade d where d.autor_id=(objeto->>'user_id')::uuid and d.oculto_em is null),'[]'));
 elsif p_recurso='fontes' then
  select coalesce(jsonb_agg(x.item),'[]') into itens from (select jsonb_build_object('chunk_id',c.chunk_id,'titulo',f.titulo,'autor_orgao',f.autor_orgao,'paginas',c.paginas,'trecho',left(c.conteudo,2000),'url_origem',f.url_origem) item from chunks c join fontes f using(fonte_id) where char_length(coalesce(p_dados->>'q',''))>=3 and (f.titulo ilike '%'||(p_dados->>'q')||'%' or c.conteudo ilike '%'||(p_dados->>'q')||'%') order by f.titulo,c.ordem limit 20 offset inicio) x; select count(*) into total from chunks c join fontes f using(fonte_id) where char_length(coalesce(p_dados->>'q',''))>=3 and (f.titulo ilike '%'||(p_dados->>'q')||'%' or c.conteudo ilike '%'||(p_dados->>'q')||'%');
 elsif p_recurso='notificacoes' then
  select count(*) into total from notificacoes_comunidade n where membro_id=p_ator and comunidade_visivel((n.dados->>'discussao_id')::uuid);
  select coalesce(jsonb_agg(x.item),'[]') into itens from (select jsonb_build_object('notificacao_id',n.notificacao_id,'tipo',n.tipo,'dados',n.dados,'lida_em',n.lida_em,'criada_em',n.criada_em) item from notificacoes_comunidade n where membro_id=p_ator and comunidade_visivel((n.dados->>'discussao_id')::uuid) order by criada_em desc limit 20 offset inicio) x;
 elsif p_recurso in ('transparencia','ouro') then
  if p_recurso='ouro' then
   select count(*) into total from respostas_ouro o join propostas_versoes v using(versao_id) join propostas_comunidade p using(proposta_id) where p.estado<>'oculta' and comunidade_visivel(p.discussao_id) and (p_dados->>'id' is null or o.ouro_id=(p_dados->>'id')::uuid);
   select coalesce(jsonb_agg(x.item),'[]') into itens from (select jsonb_build_object('ouro_id',o.ouro_id,'versao_id',o.versao_id,'titulo',o.titulo,'texto',o.texto,'estado',o.estado,'fontes_validas',o.hashes_fontes=comunidade_hashes(o.chunk_ids),'fontes',comunidade_fontes(o.chunk_ids),'discussao_id',p.discussao_id,'autor',comunidade_autor(p.autor_id)) item from respostas_ouro o join propostas_versoes v using(versao_id) join propostas_comunidade p using(proposta_id) where p.estado<>'oculta' and comunidade_visivel(p.discussao_id) and (p_dados->>'id' is null or o.ouro_id=(p_dados->>'id')::uuid) order by o.criada_em desc limit 20 offset inicio) x;
  else
   select count(*) into total from decisoes_comunidade dc join propostas_versoes v using(versao_id) join propostas_comunidade p using(proposta_id) where p.estado<>'oculta' and comunidade_visivel(p.discussao_id);
   select coalesce(jsonb_agg(x.item),'[]') into itens from (select jsonb_build_object('decisao_id',dc.decisao_id,'versao_id',dc.versao_id,'resultado',dc.resultado,'sintese',dc.sintese,'criada_em',dc.criada_em,'ciclo',dc.ciclo,'fontes',dc.fontes,'discussao_id',p.discussao_id,'pareceristas',(select jsonb_agg(coalesce(comunidade_autor(c.user_id),c.nome)) from curadores c where c.user_id=any(dc.pareceristas))) item from decisoes_comunidade dc join propostas_versoes v using(versao_id) join propostas_comunidade p using(proposta_id) where p.estado<>'oculta' and comunidade_visivel(p.discussao_id) order by dc.criada_em desc limit 20 offset inicio) x;
  end if;
  return jsonb_build_object('itens',itens,'total',total,'pagina',pagina,'eventos',coalesce((select jsonb_agg(jsonb_build_object('tipo',e.tipo,'justificativa',e.justificativa,'criado_em',e.criado_em,'atores',(select jsonb_agg(coalesce(comunidade_autor(c.user_id),c.nome)) from curadores c where c.user_id=any(e.atores)))) from (select * from eventos_governanca where tipo in ('admissao','saida','destituicao') order by criado_em desc limit 20) e),'[]'),'revisoes_ouro',coalesce((select jsonb_agg(jsonb_build_object('ouro_id',a.ouro_id,'acao',a.acao,'justificativa',a.justificativa,'criada_em',a.criada_em)) from acoes_ouro a join respostas_ouro o using(ouro_id) join propostas_versoes v using(versao_id) join propostas_comunidade p using(proposta_id) where p.estado<>'oculta' and comunidade_visivel(p.discussao_id)),'[]'));
 elsif p_recurso='curadoria' then
  perform comunidade_encaminhar_elegiveis();
  select coalesce(jsonb_agg(x.item),'[]') into itens from (select jsonb_build_object('proposta_id',p.proposta_id,'discussao_id',p.discussao_id,'titulo',d.titulo,'autor',comunidade_autor(p.autor_id),'versao',comunidade_versao(v.versao_id,p_ator),'impedido',comunidade_impedido(v.versao_id,p_ator)) item from propostas_versoes v join propostas_comunidade p using(proposta_id) join discussoes_comunidade d using(discussao_id) where v.numero=p.versao_atual and v.estado in ('aberta','encaminhada','recorrida') and p.estado<>'oculta' and d.oculto_em is null order by case when v.estado in ('encaminhada','recorrida') then 0 else 1 end,(select count(*) filter(where tipo='apoio')-count(*) filter(where tipo<>'apoio') from avaliacoes_proposta a where a.versao_id=v.versao_id) desc,v.criada_em limit 20 offset inicio) x;
  return jsonb_build_object('itens',itens,'pagina',pagina,'curadores',coalesce((select jsonb_agg(jsonb_build_object('user_id',c.user_id,'nome',c.nome,'ativo',c.ativo)) from curadores c),'[]'),
   'candidaturas',coalesce((select jsonb_agg(jsonb_build_object('candidatura_id',ca.candidatura_id,'candidato',comunidade_autor(ca.candidato_id),'consentido_em',ca.consentido_em,'votos',(select jsonb_agg(jsonb_build_object('curador_id',vc.curador_id,'aprova',vc.aprova)) from votos_candidatura vc where vc.candidatura_id=ca.candidatura_id))) from candidaturas_curadoria ca where estado='pendente'),'[]'),
   'destituicoes',coalesce((select jsonb_agg(jsonb_build_object('destituicao_id',de.destituicao_id,'alvo_id',de.alvo_id,'justificativa',de.justificativa,'defesa',de.defesa,'criado_em',de.criado_em)) from destituicoes_curadoria de where estado='pendente'),'[]'),
   'denuncias',coalesce((select jsonb_agg(to_jsonb(x)) from (select denuncia_id,alvo_tipo,alvo_id,motivo from denuncias_comunidade where estado='pendente' limit 100) x),'[]'),
   'moderacoes',coalesce((select jsonb_agg(to_jsonb(x)) from (select moderacao_id,alvo_tipo,alvo_id,acao,justificativa from moderacoes_comunidade order by criada_em desc limit 100) x),'[]'),
   'recursos',coalesce((select jsonb_agg(to_jsonb(x)) from (select recurso_id,alvo_tipo,alvo_id,motivo from recursos_comunidade where estado='pendente' limit 100) x),'[]'));
 else raise exception 'RECURSO_DESCONHECIDO'; end if;
 return jsonb_build_object('itens',itens,'total',total,'pagina',pagina);
end $$;
revoke all on function comunidade_versao(uuid,uuid), comunidade_consultar(text,jsonb,uuid) from public,anon,authenticated;
grant execute on function comunidade_versao(uuid,uuid), comunidade_consultar(text,jsonb,uuid) to service_role;
grant select,insert,update,delete on all tables in schema public to service_role;
